
GPIO_PIN_SERVO = 18
GPIO_PIN_RELY_1 = 23
GPIO_PIN_RELY_2 = 24
GPIO_MOTION = 17
GPIO_LIGHT_SENSOR = 16

# servo configs
SERVO_MOVE_DELAY = 0.5
SERVO_POS_LEFT = 3
SERVO_POS_RIGHT = 14
SERVO_POS_CENTER = 7.5

# light sensor config
LIGHT_SENSOR_DARK_INDEX = 10000

# default light config
DEFAULT_DOOR_LIGHT = 1